/**
 * The game-facing Nova API client (S1).
 *
 * `createNovaClient(backend)` builds the exact object games receive as
 * `window.nova` (the in-frame bridge and the arena construct the same client
 * over different backends, so game code behaves identically in both). The
 * client is a thin, lifecycle-enforced projection over a
 * {@link NovaClientBackend}:
 *
 * - it enforces the lifecycle (registration → ready → start → end) and makes
 *   every call that requires a later stage fail with a clear
 *   {@link NovaError} (S1 acceptance: API calls fail clearly before
 *   readiness; unknown methods or versions fail safely);
 * - it validates every input against the same bounded schemas used at the
 *   protocol boundary (no `any`, never trust game input);
 * - inbound events arrive as plain data ({@link NovaSessionEvent}) and are
 *   dispatched to the game's handlers inside this context — functions
 *   registered by a game never cross the frame, only data does.
 */
import { isSupportedApiVersion } from "./version";
import {
  NOVA_ERROR_CODES,
  NovaError,
  endedMessage,
  notStartedMessage,
  type NovaErrorCode,
} from "./errors";
import { isReservedChannelName } from "./constants";
import { newActionId } from "./ids";
import {
  MEDIA_PUBLISH_INPUT_MESSAGE,
  isMediaInput,
  mediaUnsupportedError,
  probeMediaSupport,
} from "./media";
import {
  assertStructuredCloneSafe,
  assertValid,
  isBinaryPayload,
  novaActionSchema,
  novaChannelNameSchema,
  novaGameDeclarationSchema,
  novaRawChannelSpecSchema,
  novaSimulationInputSchema,
} from "./validation";
import { NOVA_ACTION_TIMEOUT_MS } from "./types";
import type {
  NovaAction,
  NovaActionAck,
  NovaApi,
  NovaConnectionStatus,
  NovaGameDeclaration,
  NovaPlayer,
  NovaRawChannelSpec,
  NovaRawHandle,
  NovaRawMessage,
  NovaRawSendOptions,
  NovaSimulationHandle,
  NovaSimulationHandlers,
  NovaSimulationInput,
  NovaSimulationSnapshot,
  NovaStateHandle,
  NovaStateHandlers,
  NovaMediaHandle,
} from "./types";

/**
 * Every event a session backend can push to a client. Only the client-event
 * kinds below are forwarded to game handlers; host-side events such as
 * `actionReceived` (the S2 authority seam) are ignored by the client.
 */
export type NovaSessionEvent =
  | { type: "playerJoined"; player: NovaPlayer }
  | { type: "playerLeft"; player: NovaPlayer }
  | { type: "connection"; status: NovaConnectionStatus }
  | { type: "start" }
  | { type: "end"; reason: string }
  | { type: "state"; state: unknown }
  | { type: "rawMessage"; channel: string; message: NovaRawMessage }
  | { type: "simulationInput"; input: NovaSimulationInput & { sender: NovaPlayer } }
  | { type: "simulationSnapshot"; snapshot: NovaSimulationSnapshot }
  /** The local simulation clock advanced one time step (A1). */
  | { type: "simulationTick"; tick: number }
  /**
   * The game's authority changed (A1). Games never learn which player is
   * authoritative — the event carries the monotonic term only, and the
   * next snapshot is the restore point.
   */
  | { type: "simulationAuthorityChange"; term: number }
  | { type: "error"; error: NovaError }
  | { type: "actionReceived"; action: NovaAction }
  | { type: "actionAck"; ack: NovaActionAck }
  | {
      type: "stateCommitted";
      revision: number;
      stateHash: string | null;
      stateSizeBytes: number;
      appliedCount: number;
      rejectedCount: number;
      actionRatePerSecond: number;
    }
  | { type: "actionRejected"; actionId: string; code: string; message: string }
  | {
      /** S3: the authority changed (election/migration). Host-side only. */
      type: "authorityChanged";
      authorityMemberId: string | null;
      term: number;
    };

/**
 * The backend a client is projected over: the in-process session engine or
 * the in-frame bridge. The interface is data-only — functions registered by
 * a game stay in the client, never crossing the frame (S1 design goal).
 */
export interface NovaClientBackend {
  /** API version this backend speaks (matches `nova.version`). */
  readonly apiVersion: number;
  /** This player's identity, or null before the host provides one. */
  readonly self: NovaPlayer | null;
  /**
   * Accept the game registration. State-mode handler functions stay in the
   * game's own context and are passed separately from the plain-data
   * declaration.
   */
  register(declaration: NovaGameDeclaration, handlers?: NovaStateHandlers): void;
  /** Announce the game is ready to play. */
  ready(): void;
  /**
   * Dispatch one action (state mode); `actionId` is generated by the caller
   * (frame or client) so acks can be correlated. Resolves once Nova
   * accepted the action for delivery.
   */
  dispatch(action: NovaAction, actionId: string): Promise<void>;
  /** Declare a raw channel to the party. */
  createRawChannel(spec: NovaRawChannelSpec): void;
  /** Close a raw channel and tell the party. */
  closeRawChannel(name: string): void;
  /** Send a payload on a raw channel. */
  sendRaw(name: string, payload: unknown, options?: NovaRawSendOptions): void;
  /** Signal that the game registered simulation handlers. */
  registerSimulation(handlers?: NovaSimulationHandlers): void;
  /** Send one simulation input to the party. */
  sendSimulationInput(input: NovaSimulationInput): void;
  /** Subscribe to inbound events. Returns an unsubscribe function. */
  onEvent(handler: (event: NovaSessionEvent) => void): () => void;
}

/** The client object games receive, plus the host-side `dispose`. */
export interface NovaClient extends NovaApi {
  /** Detach from the backend and clear all handlers (host/arena use). */
  dispose(): void;
}

type Handler<T> = (value: T) => void;

function addHandler<T>(set: Set<Handler<T>>, handler: Handler<T>): () => void {
  set.add(handler);
  return () => {
    set.delete(handler);
  };
}

/**
 * Invoke every handler, isolating game code: a throwing handler must never
 * break the event loop or the next handler (mirrors the frame bridge).
 */
function callSafely<T>(handlers: Iterable<Handler<T>>, arg?: T): void {
  for (const handler of handlers) {
    try {
      if (arg === undefined) {
        (handler as () => void)();
      } else {
        handler(arg);
      }
    } catch {
      // Game-originated handler exceptions never break Nova.
    }
  }
}

/** Build the game-facing API object over a backend (see module docs). */
export function createNovaClient(backend: NovaClientBackend): NovaClient {
  let registered = false;
  let readySent = false;
  let started = false;
  let ended = false;
  let stateValue: unknown | null = null;
  let renderHandler: ((view: unknown) => void) | null = null;
  /** The latest state received before start (delivered on the start event). */
  let bufferedState: { has: boolean; value: unknown } = { has: false, value: null };

  /** Dispatches awaiting the authority's ack, keyed by action id. */
  const pendingDispatches = new Map<
    string,
    {
      resolve: () => void;
      reject: (error: NovaError) => void;
      timer: ReturnType<typeof setTimeout>;
    }
  >();

  const players: NovaPlayer[] = backend.self === null ? [] : [backend.self];
  const joinHandlers = new Set<Handler<NovaPlayer>>();
  const leaveHandlers = new Set<Handler<NovaPlayer>>();
  const connectionHandlers = new Set<Handler<NovaConnectionStatus>>();
  const startHandlers = new Set<Handler<void>>();
  const endHandlers = new Set<Handler<string>>();
  const errorHandlers = new Set<Handler<NovaError>>();
  const stateHandlers = new Set<Handler<unknown>>();
  const rawHandlers = new Map<string, Set<Handler<NovaRawMessage>>>();
  let simulationHandlers: NovaSimulationHandlers | null = null;
  let simulationTick = 0;
  const simulationAuthorityChangeHandlers = new Set<Handler<void>>();

  const unsubscribeEvents = backend.onEvent((event) => {
    switch (event.type) {
      case "playerJoined":
        if (!players.some((player) => player.id === event.player.id)) {
          players.push(event.player);
        }
        callSafely(joinHandlers, event.player);
        break;
      case "playerLeft": {
        const index = players.findIndex((player) => player.id === event.player.id);
        if (index >= 0) {
          players.splice(index, 1);
        }
        callSafely(leaveHandlers, event.player);
        break;
      }
      case "connection":
        client.connectionStatus = event.status;
        callSafely(connectionHandlers, event.status);
        break;
      case "start":
        started = true;
        // Deliver the initial view (which can precede the start event on the
        // same ordered channel) so games see their state before onStart runs
        // and can dispatch from state.onChange immediately.
        if (bufferedState.has) {
          stateValue = bufferedState.value;
          bufferedState = { has: false, value: null };
          callSafely(stateHandlers, stateValue);
          if (renderHandler !== null) {
            callSafely(new Set([renderHandler]), stateValue);
          }
        }
        callSafely(startHandlers);
        break;
      case "end":
        ended = true;
        callSafely(endHandlers, event.reason);
        break;
      case "state":
        if (!started) {
          // Pre-start views (the initial snapshot's view on the same ordered
          // channel) are buffered and delivered with the start event.
          bufferedState = { has: true, value: event.state };
          break;
        }
        stateValue = event.state;
        callSafely(stateHandlers, event.state);
        if (renderHandler !== null) {
          callSafely(new Set([renderHandler]), event.state);
        }
        break;
      case "rawMessage": {
        const handlers = rawHandlers.get(event.channel);
        if (handlers === undefined) {
          break; // no subscription: drop (documented raw-channel rule)
        }
        callSafely(handlers, event.message);
        break;
      }
      case "simulationInput":
        if (simulationHandlers?.onInput !== undefined) {
          callSafely(new Set([simulationHandlers.onInput]), event.input);
        }
        break;
      case "simulationSnapshot":
        if (simulationHandlers?.onSnapshot !== undefined) {
          callSafely(new Set([simulationHandlers.onSnapshot]), event.snapshot);
        }
        break;
      case "simulationTick":
        simulationTick = event.tick;
        if (simulationHandlers?.onTick !== undefined) {
          callSafely(new Set([simulationHandlers.onTick]), event.tick);
        }
        break;
      case "simulationAuthorityChange":
        // Games never learn which player is authoritative: a bare
        // notification (the next snapshot is the restore point).
        callSafely(simulationAuthorityChangeHandlers);
        break;
      case "error":
        callSafely(errorHandlers, event.error);
        break;
      case "actionReceived":
        break; // host-side seam; games never see raw actions
      case "actionAck": {
        const entry = pendingDispatches.get(event.ack.actionId);
        if (entry === undefined) {
          break; // duplicate ack or unknown action id
        }
        pendingDispatches.delete(event.ack.actionId);
        clearTimeout(entry.timer);
        if (event.ack.status === "accepted") {
          entry.resolve();
        } else {
          entry.reject(
            new NovaError(
              toErrorCode(event.ack.errorCode),
              event.ack.errorMessage ?? "The action was rejected by the authority.",
            ),
          );
        }
        break;
      }
      case "stateCommitted":
      case "actionRejected":
      case "authorityChanged":
        break; // host-side diagnostics; games observe acks and errors
    }
  });

  const stateHandle: NovaStateHandle = {
    get() {
      return stateValue;
    },
    onChange(handler) {
      return addHandler(stateHandlers, handler);
    },
  };

  const rawHandle: NovaRawHandle = {
    createChannel(spec) {
      if (ended) throw new NovaError("ended", endedMessage("raw.createChannel"));
      if (!started) throw new NovaError("not_started", notStartedMessage("raw.createChannel"));
      const parsed = novaRawChannelSpecSchema.safeParse(spec);
      assertValid(parsed.success, "nova.raw.createChannel options failed validation.");
      if (isReservedChannelName(spec.name)) {
        throw new NovaError(
          "reserved_channel",
          `Raw channel name "${spec.name}" is reserved by the Nova protocol.`,
        );
      }
      backend.createRawChannel(spec);
    },
    close(name) {
      if (ended) throw new NovaError("ended", endedMessage("raw.close"));
      if (!started) throw new NovaError("not_started", notStartedMessage("raw.close"));
      assertValid(
        novaChannelNameSchema.safeParse(name).success,
        "nova.raw.close: bad channel name.",
      );
      backend.closeRawChannel(name);
    },
    send(name, payload, options = {}) {
      if (ended) throw new NovaError("ended", endedMessage("raw.send"));
      if (!started) throw new NovaError("not_started", notStartedMessage("raw.send"));
      assertValid(
        novaChannelNameSchema.safeParse(name).success,
        "nova.raw.send: bad channel name.",
      );
      if (options.onProgress !== undefined && typeof options.onProgress !== "function") {
        throw new NovaError(
          "invalid_options",
          "nova.raw.send options.onProgress must be a function.",
        );
      }
      if (!isBinaryPayload(payload)) {
        assertStructuredCloneSafe(payload, `nova.raw.send payload on channel "${name}"`);
      }
      // The session validates channels, limits, and connectivity asynchronously
      // (transport send); failures are delivered to `nova.onError` handlers so
      // games observe them uniformly in the arena, over party transports, and
      // in-process (S1: every API failure is a stable NovaError).
      Promise.resolve()
        .then(() => backend.sendRaw(name, payload, options))
        .catch((error: unknown) => {
          callSafely(
            errorHandlers,
            error instanceof NovaError ? error : new NovaError("invalid_options", String(error)),
          );
        });
    },
    onMessage(name, handler) {
      assertValid(
        novaChannelNameSchema.safeParse(name).success,
        "nova.raw.onMessage: bad channel name.",
      );
      let handlers = rawHandlers.get(name);
      if (handlers === undefined) {
        handlers = new Set();
        rawHandlers.set(name, handlers);
      }
      return addHandler(handlers, handler);
    },
  };

  const simulationHandle: NovaSimulationHandle = {
    register(handlers) {
      const onInput = handlers.onInput;
      const onSnapshot = handlers.onSnapshot;
      const onTick = handlers.onTick;
      const serializeState = handlers.serializeState;
      if (
        (onInput !== undefined && typeof onInput !== "function") ||
        (onSnapshot !== undefined && typeof onSnapshot !== "function") ||
        (onTick !== undefined && typeof onTick !== "function") ||
        (serializeState !== undefined && typeof serializeState !== "function")
      ) {
        throw new NovaError(
          "invalid_options",
          "nova.simulation.register expects onInput/onSnapshot/onTick/serializeState functions.",
        );
      }
      simulationHandlers = handlers;
      backend.registerSimulation(handlers);
      return () => {
        if (simulationHandlers === handlers) {
          simulationHandlers = null;
        }
      };
    },
    sendInput(input) {
      if (ended) throw new NovaError("ended", endedMessage("simulation.sendInput"));
      if (!started) throw new NovaError("not_started", notStartedMessage("simulation.sendInput"));
      assertValid(
        novaSimulationInputSchema.safeParse(input).success,
        "nova.simulation.sendInput options failed validation.",
      );
      assertStructuredCloneSafe(input.payload, "nova.simulation.sendInput payload");
      // Runtime rejections (rate limit, not connected) arrive via
      // `nova.onError` so games observe them uniformly in the arena, over
      // party transports, and in-process (S1: every API failure is a
      // stable NovaError).
      Promise.resolve()
        .then(() => backend.sendSimulationInput(input))
        .catch((error: unknown) => {
          callSafely(
            errorHandlers,
            error instanceof NovaError ? error : new NovaError("invalid_options", String(error)),
          );
        });
    },
    onAuthorityChange(handler) {
      return addHandler(simulationAuthorityChangeHandlers, handler);
    },
    getTick() {
      return simulationTick;
    },
  };

  // A3 experimental media surface: probe platform capability, and fail
  // clearly when a game tries to publish (media transport cannot cross the
  // frame boundary in this build — see docs/testing/media-bridging-findings.md).
  // Publish never reaches the backend: there is no media transport path yet.
  const mediaHandle: NovaMediaHandle = {
    isSupported() {
      return probeMediaSupport();
    },
    publish(trackOrStream) {
      // Lifecycle gating mirrors every sending call (S1): media needs a
      // live party connection, which only exists after start.
      if (ended) throw new NovaError("ended", endedMessage("media.publish"));
      if (!started) throw new NovaError("not_started", notStartedMessage("media.publish"));
      if (!isMediaInput(trackOrStream)) {
        throw new NovaError("invalid_options", MEDIA_PUBLISH_INPUT_MESSAGE);
      }
      throw mediaUnsupportedError();
    },
  };

  const client: NovaClient = {
    version: backend.apiVersion,
    defineGame(options) {
      if (registered) {
        throw new NovaError(
          "already_registered",
          "nova.defineGame() was already called; call it exactly once.",
        );
      }
      const parsed = novaGameDeclarationSchema.safeParse(options);
      assertValid(parsed.success, "nova.defineGame options failed validation.");
      if (options.apiVersion !== undefined && !isSupportedApiVersion(options.apiVersion)) {
        throw new NovaError(
          "unsupported_api_version",
          `nova.defineGame() targets API version ${String(options.apiVersion)}, but this build supports version(s) [1].`,
        );
      }
      // Validate the handler functions before committing the registration so
      // a failed defineGame leaves the client unregistered.
      const handlers = extractStateHandlers(options);
      registered = true;
      if (handlers?.render !== undefined) {
        renderHandler = handlers.render;
      }
      // The declaration that crosses the backend boundary is plain data
      // only: handler functions stay in this context (never serialized).
      const declaration: NovaGameDeclaration = {
        ...(options.title !== undefined ? { title: options.title } : {}),
        ...(options.mode !== undefined ? { mode: options.mode } : {}),
        ...(options.version !== undefined ? { version: options.version } : {}),
        ...(options.apiVersion !== undefined ? { apiVersion: options.apiVersion } : {}),
      };
      backend.register(declaration, handlers);
    },
    ready() {
      if (!registered) {
        throw new NovaError(
          "not_registered",
          "nova.ready() must be called after nova.defineGame().",
        );
      }
      if (ended) {
        throw new NovaError("ended", endedMessage("ready"));
      }
      if (started) {
        throw new NovaError(
          "already_started",
          "nova.ready() is not available after the game starts.",
        );
      }
      if (readySent) {
        throw new NovaError("already_ready", "nova.ready() was already called.");
      }
      readySent = true;
      backend.ready();
    },
    log(...args) {
      console.log(...args);
    },
    get player() {
      return backend.self;
    },
    get players() {
      return [...players];
    },
    connectionStatus: "disconnected",
    onPlayerJoin(handler) {
      return addHandler(joinHandlers, handler);
    },
    onPlayerLeave(handler) {
      return addHandler(leaveHandlers, handler);
    },
    onConnectionChange(handler) {
      return addHandler(connectionHandlers, handler);
    },
    onStart(handler) {
      return addHandler(startHandlers, handler);
    },
    onEnd(handler) {
      return addHandler(endHandlers, handler);
    },
    onError(handler) {
      return addHandler(errorHandlers, handler);
    },
    dispatch(action) {
      if (ended) throw new NovaError("ended", endedMessage("dispatch"));
      if (!started) throw new NovaError("not_started", notStartedMessage("dispatch"));
      assertValid(
        novaActionSchema.safeParse(action).success,
        "nova.dispatch options failed validation.",
      );
      assertStructuredCloneSafe(action.payload, "nova.dispatch action payload");
      // The action id is generated here so the authority's ack can be
      // correlated with this promise (S2: dispatch resolves on the ack).
      const actionId = newActionId();
      const pending = new Promise<void>((resolve, reject) => {
        const timer = setTimeout(() => {
          pendingDispatches.delete(actionId);
          reject(
            new NovaError("timed_out", "The action timed out waiting for the authority's ack."),
          );
        }, NOVA_ACTION_TIMEOUT_MS + 2000);
        pendingDispatches.set(actionId, { resolve, reject, timer });
      });
      Promise.resolve()
        .then(() => backend.dispatch(action, actionId))
        .catch((error: unknown) => {
          const entry = pendingDispatches.get(actionId);
          if (entry === undefined) return;
          pendingDispatches.delete(actionId);
          clearTimeout(entry.timer);
          entry.reject(
            error instanceof NovaError ? error : new NovaError("invalid_options", String(error)),
          );
        });
      return pending;
    },
    get state() {
      return stateHandle;
    },
    get raw() {
      return rawHandle;
    },
    get simulation() {
      return simulationHandle;
    },
    get media() {
      return mediaHandle;
    },
    dispose() {
      unsubscribeEvents();
      joinHandlers.clear();
      leaveHandlers.clear();
      connectionHandlers.clear();
      startHandlers.clear();
      endHandlers.clear();
      errorHandlers.clear();
      stateHandlers.clear();
      rawHandlers.clear();
      simulationHandlers = null;
      simulationAuthorityChangeHandlers.clear();
      renderHandler = null;
      for (const entry of pendingDispatches.values()) {
        clearTimeout(entry.timer);
        entry.reject(
          new NovaError("ended", "The session was disposed before the action was applied."),
        );
      }
      pendingDispatches.clear();
    },
  };

  return client;
}

/** Pull state-mode handler functions out of a declaration and validate them. */
function extractStateHandlers(options: NovaGameDeclaration): NovaStateHandlers | undefined {
  const declared =
    options.createInitialState !== undefined ||
    options.actions !== undefined ||
    options.selectView !== undefined ||
    options.render !== undefined;
  if (!declared) return undefined;
  const handlers: NovaStateHandlers = {};
  if (options.createInitialState !== undefined) {
    if (typeof options.createInitialState !== "function") {
      throw new NovaError(
        "invalid_options",
        "nova.defineGame: createInitialState must be a function.",
      );
    }
    handlers.createInitialState = options.createInitialState;
  }
  if (options.selectView !== undefined) {
    if (typeof options.selectView !== "function") {
      throw new NovaError("invalid_options", "nova.defineGame: selectView must be a function.");
    }
    handlers.selectView = options.selectView;
  }
  if (options.render !== undefined) {
    if (typeof options.render !== "function") {
      throw new NovaError("invalid_options", "nova.defineGame: render must be a function.");
    }
    handlers.render = options.render;
  }
  if (options.actions !== undefined) {
    if (typeof options.actions !== "object" || options.actions === null) {
      throw new NovaError(
        "invalid_options",
        "nova.defineGame: actions must be an object of handlers.",
      );
    }
    for (const [name, handler] of Object.entries(options.actions)) {
      if (typeof handler !== "function") {
        throw new NovaError(
          "invalid_options",
          `nova.defineGame: action "${name}" must be a function.`,
        );
      }
    }
    handlers.actions = options.actions;
  }
  return handlers;
}

/** Map an ack error code onto the stable NovaError code set. */
function toErrorCode(code: string | undefined): NovaErrorCode {
  if (code !== undefined && code in NOVA_ERROR_CODES) {
    return code as NovaErrorCode;
  }
  return "invalid_options";
}
