/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BuildRouteImport } from './routes/build'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PartyRouteImport } from './routes/party'
import { Route as ClassicGameIdRouteImport } from './routes/classic/$gameId'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as GamesGameIdEditRouteImport } from './routes/games/$gameId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicGameIdRoute = ClassicGameIdRouteImport.update({
  id: '/classic/$gameId',
  path: '/classic/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: '/games/$gameId/edit',
  path: '/games/$gameId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/build': typeof BuildRoute
  '/editor': typeof EditorRoute
  '/examples': typeof ExamplesRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/classic/$gameId': typeof ClassicGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/build': typeof BuildRoute
  '/editor': typeof EditorRoute
  '/examples': typeof ExamplesRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/classic/$gameId': typeof ClassicGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/build': typeof BuildRoute
  '/editor': typeof EditorRoute
  '/examples': typeof ExamplesRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/classic/$gameId': typeof ClassicGameIdRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/build'
    | '/editor'
    | '/examples'
    | '/join'
    | '/library'
    | '/party'
    | '/classic/$gameId'
    | '/game/$gameId'
    | '/games/$gameId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/build'
    | '/editor'
    | '/examples'
    | '/join'
    | '/library'
    | '/party'
    | '/classic/$gameId'
    | '/game/$gameId'
    | '/games/$gameId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/build'
    | '/editor'
    | '/examples'
    | '/join'
    | '/library'
    | '/party'
    | '/classic/$gameId'
    | '/game/$gameId'
    | '/games/$gameId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  BuildRoute: typeof BuildRoute
  EditorRoute: typeof EditorRoute
  ExamplesRoute: typeof ExamplesRoute
  JoinRoute: typeof JoinRoute
  LibraryRoute: typeof LibraryRoute
  PartyRoute: typeof PartyRoute
  ClassicGameIdRoute: typeof ClassicGameIdRoute
  GameGameIdRoute: typeof GameGameIdRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/$gameId': {
      id: '/classic/$gameId'
      path: '/classic/$gameId'
      fullPath: '/classic/$gameId'
      preLoaderRoute: typeof ClassicGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/edit': {
      id: '/games/$gameId/edit'
      path: '/games/$gameId/edit'
      fullPath: '/games/$gameId/edit'
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  BuildRoute: BuildRoute,
  EditorRoute: EditorRoute,
  ExamplesRoute: ExamplesRoute,
  JoinRoute: JoinRoute,
  LibraryRoute: LibraryRoute,
  PartyRoute: PartyRoute,
  ClassicGameIdRoute: ClassicGameIdRoute,
  GameGameIdRoute: GameGameIdRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
