/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreateRouteImport } from './routes/create'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PartyRouteImport } from './routes/party'
import { Route as PlayRouteImport } from './routes/play'
import { Route as GamesGameIdEditRouteImport } from './routes/games/$gameId/edit'
import { Route as GamesGameIdTestRouteImport } from './routes/games/$gameId/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdEditRoute = GamesGameIdEditRouteImport.update({
  id: '/games/$gameId/edit',
  path: '/games/$gameId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdTestRoute = GamesGameIdTestRouteImport.update({
  id: '/games/$gameId/test',
  path: '/games/$gameId/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/play': typeof PlayRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/games/$gameId/test': typeof GamesGameIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/play': typeof PlayRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/games/$gameId/test': typeof GamesGameIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/party': typeof PartyRoute
  '/play': typeof PlayRoute
  '/games/$gameId/edit': typeof GamesGameIdEditRoute
  '/games/$gameId/test': typeof GamesGameIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/join'
    | '/library'
    | '/party'
    | '/play'
    | '/games/$gameId/edit'
    | '/games/$gameId/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/join'
    | '/library'
    | '/party'
    | '/play'
    | '/games/$gameId/edit'
    | '/games/$gameId/test'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/join'
    | '/library'
    | '/party'
    | '/play'
    | '/games/$gameId/edit'
    | '/games/$gameId/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  LibraryRoute: typeof LibraryRoute
  PartyRoute: typeof PartyRoute
  PlayRoute: typeof PlayRoute
  GamesGameIdEditRoute: typeof GamesGameIdEditRoute
  GamesGameIdTestRoute: typeof GamesGameIdTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/edit': {
      id: '/games/$gameId/edit'
      path: '/games/$gameId/edit'
      fullPath: '/games/$gameId/edit'
      preLoaderRoute: typeof GamesGameIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/test': {
      id: '/games/$gameId/test'
      path: '/games/$gameId/test'
      fullPath: '/games/$gameId/test'
      preLoaderRoute: typeof GamesGameIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  LibraryRoute: LibraryRoute,
  PartyRoute: PartyRoute,
  PlayRoute: PlayRoute,
  GamesGameIdEditRoute: GamesGameIdEditRoute,
  GamesGameIdTestRoute: GamesGameIdTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
