/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as FindRouteImport } from './routes/find'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GameGameidRouteImport } from './routes/game.$gameid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameidRoute = GameGameidRouteImport.update({
  id: '/game/$gameid',
  path: '/game/$gameid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/find': typeof FindRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/game/$gameid': typeof GameGameidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/find': typeof FindRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/game/$gameid': typeof GameGameidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/find': typeof FindRoute
  '/join': typeof JoinRoute
  '/library': typeof LibraryRoute
  '/game/$gameid': typeof GameGameidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$code' | '/find' | '/join' | '/library' | '/game/$gameid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$code' | '/find' | '/join' | '/library' | '/game/$gameid'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/find'
    | '/join'
    | '/library'
    | '/game/$gameid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  FindRoute: typeof FindRoute
  JoinRoute: typeof JoinRoute
  LibraryRoute: typeof LibraryRoute
  GameGameidRoute: typeof GameGameidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameid': {
      id: '/game/$gameid'
      path: '/game/$gameid'
      fullPath: '/game/$gameid'
      preLoaderRoute: typeof GameGameidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  FindRoute: FindRoute,
  JoinRoute: JoinRoute,
  LibraryRoute: LibraryRoute,
  GameGameidRoute: GameGameidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
