import { z } from "zod";

/**
 * Identifier and bounded string formats shared across protocol messages.
 *
 * IDs are opaque strings with generous length bounds; the exact ID alphabet
 * is owned by the layers that generate them (nanoid-based IDs in the shell,
 * Web Crypto derived values for session material). The schemas only guarantee
 * that IDs are non-empty, bounded, and never `any`.
 */

/** Stable per-player identity within a party (ADR-0007). */
export const memberIdSchema = z.string().min(1).max(64);

/** Identifies a specific connection of a member; changes on reconnect. */
export const connectionIdSchema = z.string().min(1).max(64);

/** Unique message identifier generated by the sender. */
export const messageIdSchema = z.string().min(1).max(128);

/**
 * Party session identifier: the private room session after admission, or the
 * rendezvous session for pre-admission messages (join request, admission
 * response, party advert) so messages from colliding parties never
 * cross-correlate (ADR-0004).
 */
export const sessionIdSchema = z.string().min(1).max(128);

/** Identifies one game document. */
export const gameIdSchema = z.string().min(1).max(64);

/**
 * Identifies one runtime frame instance; a new instance gets a new ID on
 * reload or destroy (F4 spike lifecycle).
 */
export const runtimeInstanceIdSchema = z.string().min(1).max(64);

/**
 * Four-letter rendezvous namespace code (ADR-0004). The code is alphabetic
 * and normalized to uppercase before parsing; the exact human-friendly
 * alphabet is owned by P2.
 */
export const partyCodeSchema = z
  .string()
  .regex(/^[A-Z]{4}$/, "Party code must be exactly four uppercase letters A-Z.");

/**
 * The 32-byte party session secret as unpadded base64url (43 characters;
 * ADR-0011). Generated with Web Crypto (CSPRNG), carried in invite-link
 * fragments and post-admission party control messages only — never in
 * game runtime messages or the game DOM.
 */
export const sessionSecretSchema = z
  .string()
  .regex(
    /^[A-Za-z0-9_-]{43}$/,
    "Session secret must be 32 random bytes encoded as unpadded base64url.",
  );

/** Epoch-millisecond timestamp. */
export const timestampSchema = z.number().int().nonnegative();

/** Per-sender monotonic sequence number for ordered message families. */
export const monotonicSequenceSchema = z.number().int().nonnegative();

/** Player-facing display name. */
export const displayNameSchema = z.string().min(1).max(32);

/** Game title. */
export const titleSchema = z.string().min(1).max(64);

/** Named raw-mode channel identifier (ADR-0006 raw mode). */
export const channelNameSchema = z.string().min(1).max(64);

/** SHA-256 digest as 64 lowercase hex characters (ADR-0002, P3). */
export const sha256Schema = z
  .string()
  .regex(/^[0-9a-f]{64}$/, "Expected a 64-character lowercase hex SHA-256 digest.");

export type MemberId = z.infer<typeof memberIdSchema>;
export type ConnectionId = z.infer<typeof connectionIdSchema>;
export type MessageId = z.infer<typeof messageIdSchema>;
export type SessionId = z.infer<typeof sessionIdSchema>;
export type GameId = z.infer<typeof gameIdSchema>;
export type RuntimeInstanceId = z.infer<typeof runtimeInstanceIdSchema>;
export type PartyCode = z.infer<typeof partyCodeSchema>;
export type SessionSecret = z.infer<typeof sessionSecretSchema>;
export type Timestamp = z.infer<typeof timestampSchema>;
export type MonotonicSequence = z.infer<typeof monotonicSequenceSchema>;
export type DisplayName = z.infer<typeof displayNameSchema>;
export type Title = z.infer<typeof titleSchema>;
export type ChannelName = z.infer<typeof channelNameSchema>;
export type Sha256 = z.infer<typeof sha256Schema>;
