import type { ConnectionId, MemberId, MessageId, SessionId, Timestamp } from "@rocketcrab/protocol";

/**
 * Transport-neutral message and event types (ADR-0003).
 *
 * The transport layer moves payloads between party connections and reports
 * lifecycle events. It is deliberately agnostic about payload contents: the
 * runtime protocol (F6 peer schemas) formats and validates messages above
 * this layer. The delivered envelope exposes the same fields the peer
 * envelope carries (version, sessionId, senderMemberId, senderConnectionId,
 * messageId, sentAt and, for ordered families, the monotonic `seq`), so the
 * shell and adapters can correlate transport events with protocol messages.
 *
 * React-free by design; shared by InMemoryTransport (U5) and
 * TrysteroTransport (P1).
 */

/** Delivery reliability for a transport message (ADR-0006 raw mode). */
export type TransportReliability = "reliable" | "unreliable";

/** Ordering guarantee for a transport message (ADR-0006 raw mode). */
export type TransportOrdering = "ordered" | "unordered";

/**
 * Connection lifecycle of one transport. Mirrors the lifecycle expected from
 * a real party transport (F5 findings: join latency, background suspension on
 * Mobile Safari, reconnect with a fresh connection ID).
 */
export type TransportConnectionState =
  | "idle" // created but not joined
  | "joining" // join in progress (simulated discovery latency)
  | "connected" // joined to a session; messages flow
  | "suspended" // background suspension or dropped connection (threat T15)
  | "disconnected"; // left cleanly

/**
 * Payload carried by a transport message: a structured protocol message
 * (plain JSON object, validated at the protocol boundary per threat T10) or a
 * raw binary blob (ADR-0006 raw mode, P3 game-source chunks).
 */
export type TransportPayload = unknown;

/** Simulated or real peer identity as observed by a transport. */
export interface TransportPeerInfo {
  /** Stable per-player identity within a party (ADR-0007). */
  readonly memberId: MemberId;
  /** Connection identity; changes when the peer reconnects. */
  readonly connectionId: ConnectionId;
  /** Optional player-facing name when the session provides one. */
  readonly displayName?: string;
  /** Epoch-ms timestamp of the join that produced this connection. */
  readonly joinedAt: Timestamp;
}

/**
 * A message as delivered to the recipient. Envelope fields are compatible
 * with the peer envelope (F6): protocol messages additionally carry their own
 * copy of these fields inside `payload`, and adapters may assert the two
 * agree (the transport never fabricates protocol content).
 */
export interface TransportMessage {
  /** Protocol version, when the sender knows it (F6 `version`). */
  readonly version?: number;
  /** Party session ID (private room session once admitted, ADR-0004). */
  readonly sessionId: SessionId;
  /** Named channel (raw-mode channel or protocol namespace). */
  readonly channel: string;
  readonly senderMemberId: MemberId;
  readonly senderConnectionId: ConnectionId;
  /** Unique message identifier generated by the sender's transport. */
  readonly messageId: MessageId;
  /** Epoch-ms timestamp captured when the message was sent. */
  readonly sentAt: Timestamp;
  /** Per-sender monotonic sequence for ordered families (F6 `seq`). */
  readonly seq?: number;
  readonly reliability: TransportReliability;
  readonly ordering: TransportOrdering;
  /**
   * Transport-internal per-(sender connection, channel) monotonic delivery
   * stamp starting at 1, applied at send time by the transport (analogous to
   * SCTP sequence numbers). Ordered channels deliver and deduplicate by this
   * stamp; the protocol's own `seq` is carried separately for the runtime
   * layer.
   */
  readonly deliverySeq?: number;
  /** True when the payload is a raw binary blob (not a protocol message). */
  readonly binary: boolean;
  /** Set on chunk-fragment messages (progress/loss observability). */
  readonly chunkIndex?: number;
  readonly chunkCount?: number;
  readonly payload: TransportPayload;
}

/**
 * Chunked-transfer progress (F5 scenario 4: large payloads report progress on
 * both sides). The in-memory transport simulates chunked delivery; the
 * Trystero adapter maps this to Trystero's action progress callbacks.
 */
export interface TransferProgress {
  readonly direction: "send" | "receive";
  readonly messageId: MessageId;
  readonly channel: string;
  readonly bytesTransferred: number;
  readonly totalBytes: number;
  /** Fraction of the payload transferred, in [0, 1]. */
  readonly fraction: number;
}

/** Options for {@link NovaTransport.send}. */
export interface TransportSendOptions {
  /** Named channel the message travels on. */
  readonly channel: string;
  readonly payload: TransportPayload;
  /**
   * Target one peer connection; omit to broadcast to every connected peer
   * except the sender.
   */
  readonly targetConnectionId?: ConnectionId;
  /** Delivery reliability; defaults to "reliable" (Trystero default). */
  readonly reliability?: TransportReliability;
  /** Ordering guarantee; defaults to "ordered" (Trystero default). */
  readonly ordering?: TransportOrdering;
  /** Monotonic per-sender sequence for ordered families (F6 `seq`). */
  readonly seq?: number;
  /** Protocol version of the payload (F6 `version`), when known. */
  readonly version?: number;
  /**
   * True when the payload is a raw binary blob. Binary payloads bypass
   * protocol validation (ADR-0006 raw mode); structured payloads are checked
   * by the hub's validator when one is configured.
   */
  readonly binary?: boolean;
  /** Sender-side progress callback for payloads transferred in chunks. */
  readonly onProgress?: (progress: TransferProgress) => void;
}

/** Request to join a session room ({@link NovaTransport.join}). */
export interface TransportJoinRequest {
  /** Simulated room / real rendezvous room name. */
  readonly room: string;
  /** Party session ID that will label every message on this connection. */
  readonly sessionId: SessionId;
}

/** Local notification that this transport's connection was re-established. */
export interface TransportReconnectEvent {
  readonly memberId: MemberId;
  readonly oldConnectionId: ConnectionId;
  readonly newConnectionId: ConnectionId;
}

/** Transport event map: handlers receive exactly one payload per event. */
export interface TransportEventMap {
  /** A peer joined the session (post-admission join; ADR-0004). */
  "peer:joined": (peer: TransportPeerInfo) => void;
  /** A peer left, or its connection dropped (suspend / timeout; T15). */
  "peer:left": (peer: TransportPeerInfo) => void;
  /** This transport's own connection was re-established (new connection ID). */
  "peer:reconnected": (event: TransportReconnectEvent) => void;
  /** A complete message arrived and passed delivery rules. */
  "message:received": (message: TransportMessage) => void;
  /** A message (or chunk) was dropped by simulated link loss. Sender side. */
  "message:lost": (message: TransportMessage) => void;
  /** A structured payload failed the hub's validator. Sender side. */
  "message:invalid": (message: TransportMessage, reason: string) => void;
  /** Connection state of this transport changed. */
  "connection:state": (state: TransportConnectionState) => void;
  /** Chunked-transfer progress on the receive side. */
  "transfer:progress": (progress: TransferProgress) => void;
}
